### ISSUE TITLE
TODO - v1.0

### ISSUE THREAD

**Issue by pinewong** [pinewong/get-sites-web#1]
- [x] Initialization. include project create, domain register.
- [ ] Authorization system. registered user, VIP and administrator.
- [ ] File and project system.
- [ ] Web CLI.
- [ ] Debug online.
- [ ] Custom configuration.
- [ ] Quickly deploy by Docker.
