### ISSUE TITLE
TODO - v0.1

### ISSUE THREAD

**Issue by pinewong** [pinewong/get-sites-web#2]
- [x] Create `Rails 5 API` project.
- [ ] `Yard` API doc.
- [ ] The basic authorization system.
- [ ] The `cancan` system for authorization system.
