### ISSUE TITLE
TODO - v0.2

### ISSUE THREAD

**Issue by pinewong** [pinewong/get-sites-web#3]
- [ ] The frontend authorization system by Vue
- [ ] File interaction operate.
- [ ] File and project manage system online.
- [ ] Coding online. Include syntax highlight and auto complete.
