### ISSUE TITLE
TODO - v0.3

### ISSUE THREAD

**Issue by pinewong** [pinewong/get-sites-web#4]
- [ ] Web CLI.
- [ ] Docker and the environment configuration of project.
- [ ] Debug on the CLI.
- [ ] Develop online, get a near-native experience.
